###

POST http://127.0.0.1:8000/auth/signup
Content-Type: application/json

{
    "email": "test@gmail.com",
    "firstname": "test",
    "lastname": "tester",
    "password": "test",
    "gender": "F"
}

###

POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

###

POST http://127.0.0.1:8000/auth/login
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "tester"
}

###

POST http://127.0.0.1:8000/auth/logout
Content-Type: application/json

{
    "email": "test@gmail.com",
    "password": "test"
}

###

GET http://127.0.0.1:8000/feed/all
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVc2VyRGF0YSI6eyJlbWFpbCI6InRlc3RAZ21haWwuY29tIn0sImlhdCI6MTY1NDg1OTY0NywiZXhwIjoxNjU0OTQ2MDQ3fQ.Gmd0zK86CG92FHVHLA9n36G8sAmI-AmKgRawIujk8gw

{

}
